/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

//####  Usercode Components

parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};


//#### Symbol Lists

/* Terminals (tokens returned by the scanner). */
terminal PLUS;
terminal LPAREN, RPAREN, COMMA, LBRACE, RBRACE;
terminal IF, ELSE, PREFIX, SUFFIX;       
terminal String     STRING_LITERAL;  // the String means the token carries a string value
terminal String     IDENTIFIER;


/*  Non terminals */
non terminal String start_list;
non terminal String exp;
non terminal String definitions, calls, parameters, parTail, args, argsTail;
non terminal String callItem, defItem;
//, ifExp, ifCond;      



//#### Precedence Declarations

// precedence IF;
precedence left PLUS;  // PLUS(concat) has higher priority

start with start_list;

//####  The Grammar Rules

start_list ::= definitions:d calls:c         {: System.out.println(d + c); :}
            ;

definitions ::= definitions:d defItem:i {:  RESULT = d + i; :}
            | defItem:i {:  RESULT = i; :}  
            ;

defItem ::=  IDENTIFIER:i LPAREN args:p RPAREN LBRACE exp:e RBRACE   {: RESULT = i + "(" + p + ")" + "{" + "\n" + "\t" + e + "\n" + "}" + "\n"; :}
            | IDENTIFIER:i LPAREN RPAREN LBRACE exp:e RBRACE {: RESULT = i + "(" + ")" + "{" + "\n" + "\t" + e + "\n" + "}" + "\n"; :}
            ;

parameters  ::= IDENTIFIER:i                      {:  RESULT = i; :}
            | parameters:p COMMA IDENTIFIER:i    {:  RESULT = p + ", " + i; :}
            ;

exp      ::= exp:e1 PLUS exp:e2     {:  RESULT = e1 + " + " +  e2;  :} // we are building the java code
            | STRING_LITERAL:s	    {:  RESULT = "\"" +  s  +  "\"";  :}
            | IDENTIFIER:i          {:  RESULT = i; :}
            | callItem:c               {:  RESULT = c; :} // it is already a String
            //  | ifExp:
            ;
   
calls    ::= calls:c callItem:i {:  RESULT = c + i; :}
            | callItem:i        {:  RESULT = i; :}
            ;

callItem    ::= IDENTIFIER:i LPAREN args:a RPAREN   {:  RESULT = i + "(" + a + ")\n"; :}
            | IDENTIFIER:i LPAREN RPAREN  {:  RESULT = i + "()\n"; :}
            ;

args ::= args:a COMMA exp:e  {:  RESULT = a + ", " + e; :}
            | exp:e1        {:  RESULT = e1; :}
            ;
