/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;
import java.io.InputStream;
import java.io.IOException;

//####  Usercode Components

parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }

    public static String print_start_of_program(String d, String c){
    
        StringBuffer stringBuffer = new StringBuffer();

        stringBuffer.append("public class Output {\n");
        stringBuffer.append("\tpublic static void main(String[] args) {\n\t\t");
        stringBuffer.append(c);
        stringBuffer.append("\t}\n\n");
        stringBuffer.append(d);
        stringBuffer.append("}");

        return stringBuffer.toString();
    }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};


//#### Symbol Lists

/* Terminals (tokens returned by the scanner). */
terminal PLUS;
terminal RPAREN_LBRACE, LBRACE ,RBRACE, LPAREN, RPAREN, COMMA ;
terminal IF, ELSE, PREFIX, SUFFIX;       
terminal String     STRING_LITERAL;  // the String means the token carries a string value
terminal String     IDENTIFIER;


/*  Non terminals */
non terminal start_list;
non terminal String exp;
non terminal String definitions, calls, parameters, parTail, args, argsTail;
non terminal String callItem, defItem;
non terminal String ifExp;
non terminal String ifCond;      



//#### Precedence Declarations

precedence right IF;
precedence left PLUS;  // PLUS(concat) has higher priority

start with start_list;

//####  The Grammar Rules

start_list ::= definitions:d calls:c         {: System.out.println(print_start_of_program(d, c)); :}
            ;

definitions ::= definitions:d defItem:i {:  RESULT = d + i; :}
            | defItem:i {:  RESULT = i; :}  
            ;

defItem ::=  IDENTIFIER:i LPAREN args:p RPAREN LBRACE exp:e RBRACE   {: RESULT = "\tpublic static String " + i + "(" + p + "){" + "\n" + "\t\t return " + e + ";\n\t" + "}" + "\n"; :}
            | IDENTIFIER:i LPAREN RPAREN LBRACE exp:e RBRACE {: RESULT = "\tpublic static String " + i + "(){" + "\n" + "\t\t return " + e + ";\n" + "\t}" + "\n"; :}
            ;

parameters  ::= IDENTIFIER:i                      {:  RESULT = i; :}
            | parameters:p COMMA IDENTIFIER:i    {:  RESULT = p + ", " + i; :}
            ;

exp      ::= exp:e1 PLUS exp:e2     {:  RESULT = e1 + " + " +  e2;  :} // we are building the java code
            | STRING_LITERAL:s	    {:  RESULT = "\"" +  s  +  "\"";  :}
            | IDENTIFIER:i          {:  RESULT = i; :}
            | callItem:c            {:  RESULT = c; :} // it is already a String
            | ifExp:e               {: RESULT = e; :}
            ;
   
calls    ::= calls:c callItem:i {:  RESULT = c + i; :}
            | callItem:i        {:  RESULT = i; :}
            ;

callItem    ::= IDENTIFIER:i LPAREN args:a RPAREN   {:  RESULT = "System.out.println(" + i + "(" + a + "));\n"; :}
            | IDENTIFIER:i LPAREN RPAREN  {:  RESULT = "System.out.println(" + i + "());\n"; :}
            ;


args ::= args:a COMMA exp:e  {:  RESULT = a + ", " + e; :}
            | exp:e1        {:  RESULT = e1; :}
            ;

ifExp   ::= IF LPAREN ifCond:c RPAREN exp:e1 ELSE exp:e2    {:  RESULT = c + " ? " + e1 + " : " + e2 + ";\n"; :}
            ;

ifCond  ::= exp:e1 PREFIX exp:e2    {:  RESULT =  e2 + ".startsWith(" + e1 + ")"; :}
        | exp:e1 SUFFIX exp:e2  {:  RESULT = e2 + ".endsWith(" + e1 + ")"; :}
        ;